//
// Translated by CS2J (http://www.cs2j.com): 10/5/2015 1:33:57 PM
//

package Mls.Request;

import CS2JNet.JavaSupport.language.RefSupport;
import CS2JNet.System.StringSupport;
import java.util.HashMap;

public class StandardStreetName   
{
    public static HashMap<String,String[]> streetTypeDictionary;
    public static HashMap<String,String[]> streetDirectionDictionary;
    private static HashMap<String,String[]> getstreetDirectionDictionary() throws Exception {
        if (streetDirectionDictionary != null)
            return streetDirectionDictionary;
         
        streetDirectionDictionary = new HashMap<String,String[]>();
        //From Excel:="streetDirectionDictionary.Add("""&A2&""", new string[]{"""&B2&""", """&C2&"""});"
        streetDirectionDictionary.put("N", new String[]{ "North", "N" });
        streetDirectionDictionary.put("NORTH", new String[]{ "North", "N" });
        streetDirectionDictionary.put("S", new String[]{ "South", "S" });
        streetDirectionDictionary.put("SOUTH", new String[]{ "South", "S" });
        streetDirectionDictionary.put("E", new String[]{ "East", "E" });
        streetDirectionDictionary.put("EAST", new String[]{ "East", "E" });
        streetDirectionDictionary.put("W", new String[]{ "West", "W" });
        streetDirectionDictionary.put("WEST", new String[]{ "West", "W" });
        streetDirectionDictionary.put("NE", new String[]{ "North East", "NE" });
        streetDirectionDictionary.put("NORTHEAST", new String[]{ "North East", "NE" });
        streetDirectionDictionary.put("SE", new String[]{ "South East", "SE" });
        streetDirectionDictionary.put("SOUTHEAST", new String[]{ "South East", "SE" });
        streetDirectionDictionary.put("NW", new String[]{ "North West", "NW" });
        streetDirectionDictionary.put("NORTHWEST", new String[]{ "North West", "NW" });
        streetDirectionDictionary.put("SW", new String[]{ "South West", "SW" });
        streetDirectionDictionary.put("SOUTHWEST", new String[]{ "South West", "SW" });
        return streetDirectionDictionary;
    }

    private static HashMap<String,String[]> getStreetTypeDictionary() throws Exception {
        if (streetTypeDictionary != null)
            return streetTypeDictionary;
         
        streetTypeDictionary = new HashMap<String,String[]>();
        //From Excel:="streetTypeDictionary.Add("""&A2&""", new string[]{"""&B2&""", """&C2&"""});"
        streetTypeDictionary.put("ABBEY", new String[]{ "Abbey", "Abbey" });
        streetTypeDictionary.put("ACRES", new String[]{ "Acres", "Acres" });
        streetTypeDictionary.put("ALLEE", new String[]{ "Alley", "Aly" });
        streetTypeDictionary.put("ALLÉE", new String[]{ "Allée", "Allée" });
        streetTypeDictionary.put("ALLEY", new String[]{ "Alley", "Aly" });
        streetTypeDictionary.put("ALLY", new String[]{ "Alley", "Aly" });
        streetTypeDictionary.put("ALY", new String[]{ "Alley", "Aly" });
        streetTypeDictionary.put("ANEX", new String[]{ "Annex", "Anx" });
        streetTypeDictionary.put("ANNEX", new String[]{ "Annex", "Anx" });
        streetTypeDictionary.put("ANNX", new String[]{ "Annex", "Anx" });
        streetTypeDictionary.put("ANX", new String[]{ "Annex", "Anx" });
        streetTypeDictionary.put("ARC", new String[]{ "Arcade", "Arc" });
        streetTypeDictionary.put("ARCADE", new String[]{ "Arcade", "Arc" });
        streetTypeDictionary.put("AUT", new String[]{ "Autoroute", "Aut" });
        streetTypeDictionary.put("AUTOROUTE", new String[]{ "Autoroute", "Aut" });
        streetTypeDictionary.put("AV", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVE", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVEN", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVENU", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVENUE", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVN", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("AVNUE", new String[]{ "Avenue", "Ave" });
        streetTypeDictionary.put("BAY", new String[]{ "Bay", "Bay" });
        streetTypeDictionary.put("BAYOO", new String[]{ "Bayoo", "Byu" });
        streetTypeDictionary.put("BAYOU", new String[]{ "Bayoo", "Byu" });
        streetTypeDictionary.put("BCH", new String[]{ "Beach", "Bch" });
        streetTypeDictionary.put("BEACH", new String[]{ "Beach", "Bch" });
        streetTypeDictionary.put("BEND", new String[]{ "Bend", "Bnd" });
        streetTypeDictionary.put("BG", new String[]{ "Burg", "Bg" });
        streetTypeDictionary.put("BGS", new String[]{ "Burgs", "Bgs" });
        streetTypeDictionary.put("BLF", new String[]{ "Bluff", "Blf" });
        streetTypeDictionary.put("BLFS", new String[]{ "Bluffs", "Blfs" });
        streetTypeDictionary.put("BLUF", new String[]{ "Bluff", "Blf" });
        streetTypeDictionary.put("BLUFF", new String[]{ "Bluff", "Blf" });
        streetTypeDictionary.put("BLUFFS", new String[]{ "Bluffs", "Blfs" });
        streetTypeDictionary.put("BLVD", new String[]{ "Boulevard", "Blvd" });
        streetTypeDictionary.put("BND", new String[]{ "Bend", "Bnd" });
        streetTypeDictionary.put("BOT", new String[]{ "Bottom", "Btm" });
        streetTypeDictionary.put("BOTTM", new String[]{ "Bottom", "Btm" });
        streetTypeDictionary.put("BOTTOM", new String[]{ "Bottom", "Btm" });
        streetTypeDictionary.put("BOUL", new String[]{ "Boulevard", "Blvd" });
        streetTypeDictionary.put("BOULEVARD", new String[]{ "Boulevard", "Blvd" });
        streetTypeDictionary.put("BOULV", new String[]{ "Boulevard", "Blvd" });
        streetTypeDictionary.put("BR", new String[]{ "Branch", "Br" });
        streetTypeDictionary.put("BRANCH", new String[]{ "Branch", "Br" });
        streetTypeDictionary.put("BRDGE", new String[]{ "Bridge", "Brg" });
        streetTypeDictionary.put("BRG", new String[]{ "Bridge", "Brg" });
        streetTypeDictionary.put("BRIDGE", new String[]{ "Bridge", "Brg" });
        streetTypeDictionary.put("BRK", new String[]{ "Brook", "Brk" });
        streetTypeDictionary.put("BRKS", new String[]{ "Brooks", "Brks" });
        streetTypeDictionary.put("BRNCH", new String[]{ "Branch", "Br" });
        streetTypeDictionary.put("BROOK", new String[]{ "Brook", "Brk" });
        streetTypeDictionary.put("BROOKS", new String[]{ "Brooks", "Brks" });
        streetTypeDictionary.put("BTM", new String[]{ "Bottom", "Btm" });
        streetTypeDictionary.put("BURG", new String[]{ "Burg", "Bg" });
        streetTypeDictionary.put("BURGS", new String[]{ "Burgs", "Bgs" });
        streetTypeDictionary.put("BYP", new String[]{ "Bypass", "Byp" });
        streetTypeDictionary.put("BYPA", new String[]{ "Bypass", "Byp" });
        streetTypeDictionary.put("BYPAS", new String[]{ "Bypass", "Byp" });
        streetTypeDictionary.put("BYPASS", new String[]{ "Bypass", "Byp" });
        streetTypeDictionary.put("BY-PASS", new String[]{ "By-Pass", "Bypass" });
        streetTypeDictionary.put("BYPS", new String[]{ "Bypass", "Byp" });
        streetTypeDictionary.put("BYU", new String[]{ "Bayoo", "Byu" });
        streetTypeDictionary.put("BYWAY", new String[]{ "Byway", "Byway" });
        streetTypeDictionary.put("C", new String[]{ "Centre", "C" });
        streetTypeDictionary.put("CAMP", new String[]{ "Camp", "Cp" });
        streetTypeDictionary.put("CAMPUS", new String[]{ "Campus", "Campus" });
        streetTypeDictionary.put("CANYN", new String[]{ "Canyon", "Cyn" });
        streetTypeDictionary.put("CANYON", new String[]{ "Canyon", "Cyn" });
        streetTypeDictionary.put("CAPE", new String[]{ "Cape", "Cpe" });
        streetTypeDictionary.put("CAR", new String[]{ "Carré", "Car" });
        streetTypeDictionary.put("CARRÉ", new String[]{ "Carré", "Car" });
        streetTypeDictionary.put("CARREF", new String[]{ "Carrefour", "Carref" });
        streetTypeDictionary.put("CARREFOUR", new String[]{ "Carrefour", "Carref" });
        streetTypeDictionary.put("CAUSEWAY", new String[]{ "Causeway", "Cswy" });
        streetTypeDictionary.put("CAUSWAY", new String[]{ "Causeway", "Cswy" });
        streetTypeDictionary.put("CDS", new String[]{ "Cul-De-Sac", "Cds" });
        streetTypeDictionary.put("CEN", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CENT", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CENTER", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CENTERS", new String[]{ "Centers", "Ctrs" });
        streetTypeDictionary.put("CENTR", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CENTRE", new String[]{ "Centre", "Ctr" });
        streetTypeDictionary.put("CERCLE", new String[]{ "Cercle", "Cercle" });
        streetTypeDictionary.put("CH", new String[]{ "Chemin", "Ch" });
        streetTypeDictionary.put("CHASE", new String[]{ "Chase", "Chase" });
        streetTypeDictionary.put("CHEMIN", new String[]{ "Chemin", "Ch" });
        streetTypeDictionary.put("CIR", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CIRC", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CIRCL", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CIRCLE", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CIRCLES", new String[]{ "Circles", "Cirs" });
        streetTypeDictionary.put("CIRCT", new String[]{ "Circuit", "Circt" });
        streetTypeDictionary.put("CIRCUIT", new String[]{ "Circuit", "Circt" });
        streetTypeDictionary.put("CIRS", new String[]{ "Circles", "Cirs" });
        streetTypeDictionary.put("CK", new String[]{ "Creek", "Crk" });
        streetTypeDictionary.put("CLB", new String[]{ "Club", "Clb" });
        streetTypeDictionary.put("CLF", new String[]{ "Cliff", "Clf" });
        streetTypeDictionary.put("CLFS", new String[]{ "Cliffs", "Clfs" });
        streetTypeDictionary.put("CLIFF", new String[]{ "Cliff", "Clf" });
        streetTypeDictionary.put("CLIFFS", new String[]{ "Cliffs", "Clfs" });
        streetTypeDictionary.put("CLOSE", new String[]{ "Close", "Close" });
        streetTypeDictionary.put("CLUB", new String[]{ "Club", "Clb" });
        streetTypeDictionary.put("CMN", new String[]{ "Common", "Cmn" });
        streetTypeDictionary.put("CMP", new String[]{ "Camp", "Cp" });
        streetTypeDictionary.put("CNTER", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CNTR", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CNYN", new String[]{ "Canyon", "Cyn" });
        streetTypeDictionary.put("COMMON", new String[]{ "Common", "Cmn" });
        streetTypeDictionary.put("CONC", new String[]{ "Concession", "Conc" });
        streetTypeDictionary.put("CONCESSION", new String[]{ "Concession", "Conc" });
        streetTypeDictionary.put("COR", new String[]{ "Corner", "Cor" });
        streetTypeDictionary.put("CORNER", new String[]{ "Corner", "Cor" });
        streetTypeDictionary.put("CORNERS", new String[]{ "Corners", "Cors" });
        streetTypeDictionary.put("CORS", new String[]{ "Corners", "Cors" });
        streetTypeDictionary.put("CÔTE", new String[]{ "Côte", "Côte" });
        streetTypeDictionary.put("COUR", new String[]{ "Cour", "Cour" });
        streetTypeDictionary.put("COURS", new String[]{ "Cours", "Cours" });
        streetTypeDictionary.put("COURSE", new String[]{ "Course", "Crse" });
        streetTypeDictionary.put("COURT", new String[]{ "Court", "Ct" });
        streetTypeDictionary.put("COURTS", new String[]{ "Courts", "Cts" });
        streetTypeDictionary.put("COVE", new String[]{ "Cove", "Cv" });
        streetTypeDictionary.put("COVES", new String[]{ "Coves", "Cvs" });
        streetTypeDictionary.put("CP", new String[]{ "Camp", "Cp" });
        streetTypeDictionary.put("CPE", new String[]{ "Cape", "Cpe" });
        streetTypeDictionary.put("CR", new String[]{ "Creek", "Crk" });
        streetTypeDictionary.put("CRCL", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CRCLE", new String[]{ "Circle", "Cir" });
        streetTypeDictionary.put("CRECENT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CREEK", new String[]{ "Creek", "Crk" });
        streetTypeDictionary.put("CRES", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CRESCENT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CRESENT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CREST", new String[]{ "Crest", "Crst" });
        streetTypeDictionary.put("CRK", new String[]{ "Creek", "Crk" });
        streetTypeDictionary.put("CRNRS", new String[]{ "Corners", "Crnrs" });
        streetTypeDictionary.put("CROIS", new String[]{ "Croissant", "Crois" });
        streetTypeDictionary.put("CROISSANT", new String[]{ "Croissant", "Crois" });
        streetTypeDictionary.put("CROSS", new String[]{ "Crossing", "Cross" });
        streetTypeDictionary.put("CROSSING", new String[]{ "Crossing", "Xing" });
        streetTypeDictionary.put("CROSSROAD", new String[]{ "Crossroad", "Xrd" });
        streetTypeDictionary.put("CRSCNT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CRSE", new String[]{ "Course", "Crse" });
        streetTypeDictionary.put("CRSENT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CRSNT", new String[]{ "Crescent", "Cres" });
        streetTypeDictionary.put("CRSSING", new String[]{ "Crossing", "Xing" });
        streetTypeDictionary.put("CRSSNG", new String[]{ "Crossing", "Xing" });
        streetTypeDictionary.put("CRST", new String[]{ "Crest", "Crst" });
        streetTypeDictionary.put("CRT", new String[]{ "Court", "Ct" });
        streetTypeDictionary.put("CSWY", new String[]{ "Causeway", "Cswy" });
        streetTypeDictionary.put("CT", new String[]{ "Court", "Ct" });
        streetTypeDictionary.put("CTR", new String[]{ "Center", "Ctr" });
        streetTypeDictionary.put("CTRS", new String[]{ "Centers", "Ctrs" });
        streetTypeDictionary.put("CTS", new String[]{ "Courts", "Cts" });
        streetTypeDictionary.put("CUL-DE-SAC", new String[]{ "Cul-De-Sac", "Cds" });
        streetTypeDictionary.put("CURV", new String[]{ "Curve", "Curv" });
        streetTypeDictionary.put("CURVE", new String[]{ "Curve", "Curv" });
        streetTypeDictionary.put("CV", new String[]{ "Cove", "Cv" });
        streetTypeDictionary.put("CVS", new String[]{ "Coves", "Cvs" });
        streetTypeDictionary.put("CYN", new String[]{ "Canyon", "Cyn" });
        streetTypeDictionary.put("DALE", new String[]{ "Dale", "Dl" });
        streetTypeDictionary.put("DAM", new String[]{ "Dam", "Dm" });
        streetTypeDictionary.put("DELL", new String[]{ "Dell", "Dell" });
        streetTypeDictionary.put("DIV", new String[]{ "Divide", "Dv" });
        streetTypeDictionary.put("DIVERS", new String[]{ "Diversion", "Divers" });
        streetTypeDictionary.put("DIVERSION", new String[]{ "Diversion", "Divers" });
        streetTypeDictionary.put("DIVIDE", new String[]{ "Divide", "Dv" });
        streetTypeDictionary.put("DL", new String[]{ "Dale", "Dl" });
        streetTypeDictionary.put("DM", new String[]{ "Dam", "Dm" });
        streetTypeDictionary.put("DOWNS", new String[]{ "Downs", "Downs" });
        streetTypeDictionary.put("DR", new String[]{ "Drive", "Dr" });
        streetTypeDictionary.put("DRIV", new String[]{ "Drive", "Dr" });
        streetTypeDictionary.put("DRIVE", new String[]{ "Drive", "Dr" });
        streetTypeDictionary.put("DRIVES", new String[]{ "Drives", "Drs" });
        streetTypeDictionary.put("DRS", new String[]{ "Drives", "Drs" });
        streetTypeDictionary.put("DRV", new String[]{ "Drive", "Dr" });
        streetTypeDictionary.put("DV", new String[]{ "Divide", "Dv" });
        streetTypeDictionary.put("DVD", new String[]{ "Divide", "Dv" });
        streetTypeDictionary.put("ÉCH", new String[]{ "Échangeur", "Éch" });
        streetTypeDictionary.put("ÉCHANGEUR", new String[]{ "Échangeur", "Éch" });
        streetTypeDictionary.put("END", new String[]{ "End", "End" });
        streetTypeDictionary.put("ESPL", new String[]{ "Esplanade", "Espl" });
        streetTypeDictionary.put("ESPLANADE", new String[]{ "Esplanade", "Espl" });
        streetTypeDictionary.put("EST", new String[]{ "Estate", "Est" });
        streetTypeDictionary.put("ESTATE", new String[]{ "Estate", "Est" });
        streetTypeDictionary.put("ESTATES", new String[]{ "Estates", "Ests" });
        streetTypeDictionary.put("ESTS", new String[]{ "Estates", "Ests" });
        streetTypeDictionary.put("EXP", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXPR", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXPRESS", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXPRESSWAY", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXPW", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXPY", new String[]{ "Expressway", "Expy" });
        streetTypeDictionary.put("EXT", new String[]{ "Extension", "Ext" });
        streetTypeDictionary.put("EXTEN", new String[]{ "Extension", "Exten" });
        streetTypeDictionary.put("EXTENSION", new String[]{ "Extension", "Ext" });
        streetTypeDictionary.put("EXTENSIONS", new String[]{ "Extensions", "Exts" });
        streetTypeDictionary.put("EXTN", new String[]{ "Extension", "Ext" });
        streetTypeDictionary.put("EXTNSN", new String[]{ "Extension", "Ext" });
        streetTypeDictionary.put("EXTS", new String[]{ "Extensions", "Exts" });
        streetTypeDictionary.put("FALL", new String[]{ "Fall", "Fall" });
        streetTypeDictionary.put("FALLS", new String[]{ "Falls", "Fls" });
        streetTypeDictionary.put("FARM", new String[]{ "Farm", "Farm" });
        streetTypeDictionary.put("FERRY", new String[]{ "Ferry", "Fry" });
        streetTypeDictionary.put("FIELD", new String[]{ "Field", "Fld" });
        streetTypeDictionary.put("FIELDS", new String[]{ "Fields", "Flds" });
        streetTypeDictionary.put("FLAT", new String[]{ "Flat", "Flt" });
        streetTypeDictionary.put("FLATS", new String[]{ "Flats", "Flts" });
        streetTypeDictionary.put("FLD", new String[]{ "Field", "Fld" });
        streetTypeDictionary.put("FLDS", new String[]{ "Fields", "Flds" });
        streetTypeDictionary.put("FLS", new String[]{ "Falls", "Fls" });
        streetTypeDictionary.put("FLT", new String[]{ "Flat", "Flt" });
        streetTypeDictionary.put("FLTS", new String[]{ "Flats", "Flts" });
        streetTypeDictionary.put("FORD", new String[]{ "Ford", "Frd" });
        streetTypeDictionary.put("FORDS", new String[]{ "Fords", "Frds" });
        streetTypeDictionary.put("FOREST", new String[]{ "Forest", "Frst" });
        streetTypeDictionary.put("FORESTS", new String[]{ "Forest", "Frst" });
        streetTypeDictionary.put("FORG", new String[]{ "Forge", "Frg" });
        streetTypeDictionary.put("FORGE", new String[]{ "Forge", "Frg" });
        streetTypeDictionary.put("FORGES", new String[]{ "Forges", "Frgs" });
        streetTypeDictionary.put("FORK", new String[]{ "Fork", "Frk" });
        streetTypeDictionary.put("FORKS", new String[]{ "Forks", "Frks" });
        streetTypeDictionary.put("FORT", new String[]{ "Fort", "Ft" });
        streetTypeDictionary.put("FRD", new String[]{ "Ford", "Frd" });
        streetTypeDictionary.put("FRDS", new String[]{ "Fords", "Frds" });
        streetTypeDictionary.put("FREEWAY", new String[]{ "Freeway", "Fwy" });
        streetTypeDictionary.put("FREEWY", new String[]{ "Freeway", "Fwy" });
        streetTypeDictionary.put("FRG", new String[]{ "Forge", "Frg" });
        streetTypeDictionary.put("FRGS", new String[]{ "Forges", "Frgs" });
        streetTypeDictionary.put("FRK", new String[]{ "Fork", "Frk" });
        streetTypeDictionary.put("FRKS", new String[]{ "Forks", "Frks" });
        streetTypeDictionary.put("FRONT", new String[]{ "Front", "Front" });
        streetTypeDictionary.put("FRRY", new String[]{ "Ferry", "Fry" });
        streetTypeDictionary.put("FRST", new String[]{ "Forest", "Frst" });
        streetTypeDictionary.put("FRT", new String[]{ "Fort", "Ft" });
        streetTypeDictionary.put("FRWAY", new String[]{ "Freeway", "Fwy" });
        streetTypeDictionary.put("FRWY", new String[]{ "Freeway", "Fwy" });
        streetTypeDictionary.put("FRY", new String[]{ "Ferry", "Fry" });
        streetTypeDictionary.put("FT", new String[]{ "Fort", "Ft" });
        streetTypeDictionary.put("FWY", new String[]{ "Freeway", "Fwy" });
        streetTypeDictionary.put("GARDEN", new String[]{ "Garden", "Gdn" });
        streetTypeDictionary.put("GARDENS", new String[]{ "Gardens", "Gdns" });
        streetTypeDictionary.put("GARDN", new String[]{ "Garden", "Gdn" });
        streetTypeDictionary.put("GATE", new String[]{ "Gate", "Gate" });
        streetTypeDictionary.put("GATEWAY", new String[]{ "Gateway", "Gtwy" });
        streetTypeDictionary.put("GATEWY", new String[]{ "Gateway", "Gtwy" });
        streetTypeDictionary.put("GATWAY", new String[]{ "Gateway", "Gtwy" });
        streetTypeDictionary.put("GDN", new String[]{ "Garden", "Gdn" });
        streetTypeDictionary.put("GDNS", new String[]{ "Gardens", "Gdns" });
        streetTypeDictionary.put("GLADE", new String[]{ "Glade", "Glade" });
        streetTypeDictionary.put("GLEN", new String[]{ "Glen", "Gln" });
        streetTypeDictionary.put("GLENS", new String[]{ "Glens", "Glns" });
        streetTypeDictionary.put("GLN", new String[]{ "Glen", "Gln" });
        streetTypeDictionary.put("GLNS", new String[]{ "Glens", "Glns" });
        streetTypeDictionary.put("GRDEN", new String[]{ "Garden", "Gdn" });
        streetTypeDictionary.put("GRDN", new String[]{ "Garden", "Gdn" });
        streetTypeDictionary.put("GRDNS", new String[]{ "Gardens", "Gdns" });
        streetTypeDictionary.put("GREEN", new String[]{ "Green", "Grn" });
        streetTypeDictionary.put("GREENS", new String[]{ "Greens", "Grns" });
        streetTypeDictionary.put("GRN", new String[]{ "Green", "Grn" });
        streetTypeDictionary.put("GRNDS", new String[]{ "Grounds", "Grnds" });
        streetTypeDictionary.put("GRNS", new String[]{ "Greens", "Grns" });
        streetTypeDictionary.put("GROUNDS", new String[]{ "Grounds", "Grnds" });
        streetTypeDictionary.put("GROV", new String[]{ "Grove", "Grv" });
        streetTypeDictionary.put("GROVE", new String[]{ "Grove", "Grv" });
        streetTypeDictionary.put("GROVES", new String[]{ "Groves", "Grvs" });
        streetTypeDictionary.put("GRV", new String[]{ "Grove", "Grv" });
        streetTypeDictionary.put("GRVS", new String[]{ "Groves", "Grvs" });
        streetTypeDictionary.put("GTWAY", new String[]{ "Gateway", "Gtwy" });
        streetTypeDictionary.put("GTWY", new String[]{ "Gateway", "Gtwy" });
        streetTypeDictionary.put("HARB", new String[]{ "Harbor", "Hbr" });
        streetTypeDictionary.put("HARBOR", new String[]{ "Harbor", "Hbr" });
        streetTypeDictionary.put("HARBORS", new String[]{ "Harbors", "Hbrs" });
        streetTypeDictionary.put("HARBOUR", new String[]{ "Harbour", "Harbr" });
        streetTypeDictionary.put("HARBR", new String[]{ "Harbor", "Hbr" });
        streetTypeDictionary.put("HAVEN", new String[]{ "Haven", "Hvn" });
        streetTypeDictionary.put("HAVN", new String[]{ "Haven", "Hvn" });
        streetTypeDictionary.put("HBR", new String[]{ "Harbor", "Hbr" });
        streetTypeDictionary.put("HBRS", new String[]{ "Harbors", "Hbrs" });
        streetTypeDictionary.put("HEATH", new String[]{ "Heath", "Heath" });
        streetTypeDictionary.put("HEIGHT", new String[]{ "Heights", "Hts" });
        streetTypeDictionary.put("HEIGHTS", new String[]{ "Heights", "Hts" });
        streetTypeDictionary.put("HGHLDS", new String[]{ "Highlands", "Hghlds" });
        streetTypeDictionary.put("HGTS", new String[]{ "Heights", "Hts" });
        streetTypeDictionary.put("HIGHLANDS", new String[]{ "Highlands", "Hghlds" });
        streetTypeDictionary.put("HIGHWAY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("HIGHWY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("HILL", new String[]{ "Hill", "Hl" });
        streetTypeDictionary.put("HILLS", new String[]{ "Hills", "Hls" });
        streetTypeDictionary.put("HIWAY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("HIWY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("HL", new String[]{ "Hill", "Hl" });
        streetTypeDictionary.put("HLLW", new String[]{ "Hollow", "Holw" });
        streetTypeDictionary.put("HLS", new String[]{ "Hills", "Hls" });
        streetTypeDictionary.put("HOLLOW", new String[]{ "Hollow", "Holw" });
        streetTypeDictionary.put("HOLLOWS", new String[]{ "Hollow", "Holw" });
        streetTypeDictionary.put("HOLW", new String[]{ "Hollow", "Holw" });
        streetTypeDictionary.put("HOLWS", new String[]{ "Hollow", "Holw" });
        streetTypeDictionary.put("HRBOR", new String[]{ "Harbor", "Hbr" });
        streetTypeDictionary.put("HT", new String[]{ "Heights", "Hts" });
        streetTypeDictionary.put("HTS", new String[]{ "Heights", "Hts" });
        streetTypeDictionary.put("HVN", new String[]{ "Haven", "Hvn" });
        streetTypeDictionary.put("HWAY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("HWY", new String[]{ "Highway", "Hwy" });
        streetTypeDictionary.put("ÎLE", new String[]{ "Île", "Île" });
        streetTypeDictionary.put("IMP", new String[]{ "Impasse", "Imp" });
        streetTypeDictionary.put("IMPASSE", new String[]{ "Impasse", "Imp" });
        streetTypeDictionary.put("INLET", new String[]{ "Inlet", "Inlt" });
        streetTypeDictionary.put("INLT", new String[]{ "Inlet", "Inlt" });
        streetTypeDictionary.put("IS", new String[]{ "Island", "Is" });
        streetTypeDictionary.put("ISLAND", new String[]{ "Island", "Is" });
        streetTypeDictionary.put("ISLANDS", new String[]{ "Islands", "Iss" });
        streetTypeDictionary.put("ISLE", new String[]{ "Isle", "Isle" });
        streetTypeDictionary.put("ISLES", new String[]{ "Isle", "Isle" });
        streetTypeDictionary.put("ISLND", new String[]{ "Island", "Is" });
        streetTypeDictionary.put("ISLNDS", new String[]{ "Islands", "Iss" });
        streetTypeDictionary.put("ISS", new String[]{ "Islands", "Iss" });
        streetTypeDictionary.put("JCT", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("JCTION", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("JCTN", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("JCTNS", new String[]{ "Junctions", "Jcts" });
        streetTypeDictionary.put("JCTS", new String[]{ "Junctions", "Jcts" });
        streetTypeDictionary.put("JUNCTION", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("JUNCTIONS", new String[]{ "Junctions", "Jcts" });
        streetTypeDictionary.put("JUNCTN", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("JUNCTON", new String[]{ "Junction", "Jct" });
        streetTypeDictionary.put("KEY", new String[]{ "Key", "Ky" });
        streetTypeDictionary.put("KEYS", new String[]{ "Keys", "Kys" });
        streetTypeDictionary.put("KNL", new String[]{ "Knoll", "Knl" });
        streetTypeDictionary.put("KNLS", new String[]{ "Knolls", "Knls" });
        streetTypeDictionary.put("KNOL", new String[]{ "Knoll", "Knl" });
        streetTypeDictionary.put("KNOLL", new String[]{ "Knoll", "Knl" });
        streetTypeDictionary.put("KNOLLS", new String[]{ "Knolls", "Knls" });
        streetTypeDictionary.put("KY", new String[]{ "Key", "Ky" });
        streetTypeDictionary.put("KYS", new String[]{ "Keys", "Kys" });
        streetTypeDictionary.put("LA", new String[]{ "Lane", "Ln" });
        streetTypeDictionary.put("LAKE", new String[]{ "Lake", "Lk" });
        streetTypeDictionary.put("LAKES", new String[]{ "Lakes", "Lks" });
        streetTypeDictionary.put("LAND", new String[]{ "Land", "Land" });
        streetTypeDictionary.put("LANDING", new String[]{ "Landing", "Lndg" });
        streetTypeDictionary.put("LANDNG", new String[]{ "Landing", "Landng" });
        streetTypeDictionary.put("LANE", new String[]{ "Lane", "Ln" });
        streetTypeDictionary.put("LANES", new String[]{ "Lane", "Ln" });
        streetTypeDictionary.put("LCK", new String[]{ "Lock", "Lck" });
        streetTypeDictionary.put("LCKS", new String[]{ "Locks", "Lcks" });
        streetTypeDictionary.put("LDG", new String[]{ "Lodge", "Ldg" });
        streetTypeDictionary.put("LDGE", new String[]{ "Lodge", "Ldg" });
        streetTypeDictionary.put("LF", new String[]{ "Loaf", "Lf" });
        streetTypeDictionary.put("LGT", new String[]{ "Light", "Lgt" });
        streetTypeDictionary.put("LGTS", new String[]{ "Lights", "Lgts" });
        streetTypeDictionary.put("LIGHT", new String[]{ "Light", "Lgt" });
        streetTypeDictionary.put("LIGHTS", new String[]{ "Lights", "Lgts" });
        streetTypeDictionary.put("LIMITS", new String[]{ "Limits", "Lmts" });
        streetTypeDictionary.put("LINE", new String[]{ "Line", "Line" });
        streetTypeDictionary.put("LINK", new String[]{ "Link", "Link" });
        streetTypeDictionary.put("LK", new String[]{ "Lake", "Lk" });
        streetTypeDictionary.put("LKOUT", new String[]{ "Lookout", "Lkout" });
        streetTypeDictionary.put("LKS", new String[]{ "Lakes", "Lks" });
        streetTypeDictionary.put("LMTS", new String[]{ "Limits", "Lmts" });
        streetTypeDictionary.put("LN", new String[]{ "Lane", "Ln" });
        streetTypeDictionary.put("LNDG", new String[]{ "Landing", "Lndg" });
        streetTypeDictionary.put("LNDNG", new String[]{ "Landing", "Lndg" });
        streetTypeDictionary.put("LOAF", new String[]{ "Loaf", "Lf" });
        streetTypeDictionary.put("LOCK", new String[]{ "Lock", "Lck" });
        streetTypeDictionary.put("LOCKS", new String[]{ "Locks", "Lcks" });
        streetTypeDictionary.put("LODG", new String[]{ "Lodge", "Ldg" });
        streetTypeDictionary.put("LODGE", new String[]{ "Lodge", "Ldg" });
        streetTypeDictionary.put("LOOKOUT", new String[]{ "Lookout", "Lkout" });
        streetTypeDictionary.put("LOOP", new String[]{ "Loop", "Loop" });
        streetTypeDictionary.put("LOOPS", new String[]{ "Loop", "Loop" });
        streetTypeDictionary.put("MALL", new String[]{ "Mall", "Mall" });
        streetTypeDictionary.put("MANOR", new String[]{ "Manor", "Mnr" });
        streetTypeDictionary.put("MANORS", new String[]{ "Manors", "Mnrs" });
        streetTypeDictionary.put("MAZE", new String[]{ "Maze", "Maze" });
        streetTypeDictionary.put("MDW", new String[]{ "Meadow", "Mdw" });
        streetTypeDictionary.put("MDWS", new String[]{ "Meadows", "Mdws" });
        streetTypeDictionary.put("MEADOW", new String[]{ "Meadow", "Mdw" });
        streetTypeDictionary.put("MEADOWS", new String[]{ "Meadows", "Mdws" });
        streetTypeDictionary.put("MEDOWS", new String[]{ "Meadows", "Mdws" });
        streetTypeDictionary.put("MEWS", new String[]{ "Mews", "Mews" });
        streetTypeDictionary.put("MILL", new String[]{ "Mill", "Ml" });
        streetTypeDictionary.put("MILLS", new String[]{ "Mills", "Mls" });
        streetTypeDictionary.put("MISSION", new String[]{ "Mission", "Msn" });
        streetTypeDictionary.put("MISSN", new String[]{ "Mission", "Msn" });
        streetTypeDictionary.put("ML", new String[]{ "Mill", "Ml" });
        streetTypeDictionary.put("MLS", new String[]{ "Mills", "Mls" });
        streetTypeDictionary.put("MNR", new String[]{ "Manor", "Mnr" });
        streetTypeDictionary.put("MNRS", new String[]{ "Manors", "Mnrs" });
        streetTypeDictionary.put("MNT", new String[]{ "Mount", "Mt" });
        streetTypeDictionary.put("MNTAIN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MNTN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MNTNS", new String[]{ "Mountains", "Mtns" });
        streetTypeDictionary.put("MONTÉE", new String[]{ "Montée", "Montée" });
        streetTypeDictionary.put("MOOR", new String[]{ "Moor", "Moor" });
        streetTypeDictionary.put("MOTORWAY", new String[]{ "Motorway", "Mtwy" });
        streetTypeDictionary.put("MOUNT", new String[]{ "Mount", "Mt" });
        streetTypeDictionary.put("MOUNTAIN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MOUNTAINS", new String[]{ "Mountains", "Mtns" });
        streetTypeDictionary.put("MOUNTIN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MSN", new String[]{ "Mission", "Msn" });
        streetTypeDictionary.put("MSSN", new String[]{ "Mission", "Msn" });
        streetTypeDictionary.put("MT", new String[]{ "Mount", "Mt" });
        streetTypeDictionary.put("MTIN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MTN", new String[]{ "Mountain", "Mtn" });
        streetTypeDictionary.put("MTNS", new String[]{ "Mountains", "Mtns" });
        streetTypeDictionary.put("MTWY", new String[]{ "Motorway", "Mtwy" });
        streetTypeDictionary.put("NCK", new String[]{ "Neck", "Nck" });
        streetTypeDictionary.put("NECK", new String[]{ "Neck", "Nck" });
        streetTypeDictionary.put("OPAS", new String[]{ "Overpass", "Opas" });
        streetTypeDictionary.put("ORCH", new String[]{ "Orchard", "Orch" });
        streetTypeDictionary.put("ORCHARD", new String[]{ "Orchard", "Orch" });
        streetTypeDictionary.put("ORCHRD", new String[]{ "Orchard", "Orch" });
        streetTypeDictionary.put("OVAL", new String[]{ "Oval", "Oval" });
        streetTypeDictionary.put("OVERPASS", new String[]{ "Overpass", "Opas" });
        streetTypeDictionary.put("OVL", new String[]{ "Oval", "Oval" });
        streetTypeDictionary.put("PARADE", new String[]{ "Parade", "Parade" });
        streetTypeDictionary.put("PARC", new String[]{ "Parc", "Parc" });
        streetTypeDictionary.put("PARK", new String[]{ "Park", "Park" });
        streetTypeDictionary.put("PARKS", new String[]{ "Parks", "Park" });
        streetTypeDictionary.put("PARKWAY", new String[]{ "Parkway", "Pkwy" });
        streetTypeDictionary.put("PARKWAYS", new String[]{ "Parkways", "Pkwy" });
        streetTypeDictionary.put("PARKWY", new String[]{ "Parkway", "Pkwy" });
        streetTypeDictionary.put("PASS", new String[]{ "Pass", "Pass" });
        streetTypeDictionary.put("PASSAGE", new String[]{ "Passage", "Psge" });
        streetTypeDictionary.put("PATH", new String[]{ "Path", "Path" });
        streetTypeDictionary.put("PATHS", new String[]{ "Path", "Path" });
        streetTypeDictionary.put("PATHWAY", new String[]{ "Pathway", "Ptway" });
        streetTypeDictionary.put("PIKE", new String[]{ "Pike", "Pike" });
        streetTypeDictionary.put("PIKES", new String[]{ "Pike", "Pike" });
        streetTypeDictionary.put("PINE", new String[]{ "Pine", "Pne" });
        streetTypeDictionary.put("PINES", new String[]{ "Pines", "Pnes" });
        streetTypeDictionary.put("PK", new String[]{ "Park", "Park" });
        streetTypeDictionary.put("PKWAY", new String[]{ "Parkway", "Pkwy" });
        streetTypeDictionary.put("PKWY", new String[]{ "Parkway", "Pkwy" });
        streetTypeDictionary.put("PKWYS", new String[]{ "Parkways", "Pkwy" });
        streetTypeDictionary.put("PKY", new String[]{ "Parkway", "Pkwy" });
        streetTypeDictionary.put("PL", new String[]{ "Place", "Pl" });
        streetTypeDictionary.put("PLACE", new String[]{ "Place", "Pl" });
        streetTypeDictionary.put("PLAIN", new String[]{ "Plain", "Pln" });
        streetTypeDictionary.put("PLAINES", new String[]{ "Plains", "Plns" });
        streetTypeDictionary.put("PLAINS", new String[]{ "Plains", "Plns" });
        streetTypeDictionary.put("PLAT", new String[]{ "Plateau", "Plat" });
        streetTypeDictionary.put("PLATEAU", new String[]{ "Plateau", "Plat" });
        streetTypeDictionary.put("PLAZA", new String[]{ "Plaza", "Plz" });
        streetTypeDictionary.put("PLN", new String[]{ "Plain", "Pln" });
        streetTypeDictionary.put("PLNS", new String[]{ "Plains", "Plns" });
        streetTypeDictionary.put("PLZ", new String[]{ "Plaza", "Plz" });
        streetTypeDictionary.put("PLZA", new String[]{ "Plaza", "Plz" });
        streetTypeDictionary.put("PNE", new String[]{ "Pine", "Pne" });
        streetTypeDictionary.put("PNES", new String[]{ "Pines", "Pnes" });
        streetTypeDictionary.put("POINT", new String[]{ "Point", "Pt" });
        streetTypeDictionary.put("POINTE", new String[]{ "Pointe", "Pointe" });
        streetTypeDictionary.put("POINTS", new String[]{ "Points", "Pts" });
        streetTypeDictionary.put("PORT", new String[]{ "Port", "Prt" });
        streetTypeDictionary.put("PORTS", new String[]{ "Ports", "Prts" });
        streetTypeDictionary.put("PR", new String[]{ "Prairie", "Pr" });
        streetTypeDictionary.put("PRAIRIE", new String[]{ "Prairie", "Pr" });
        streetTypeDictionary.put("PRARIE", new String[]{ "Prairie", "Pr" });
        streetTypeDictionary.put("PRIVATE", new String[]{ "Private", "Pvt" });
        streetTypeDictionary.put("PRK", new String[]{ "Park", "Park" });
        streetTypeDictionary.put("PROM", new String[]{ "Promenade", "Prom" });
        streetTypeDictionary.put("PROMENADE", new String[]{ "Promenade", "Prom" });
        streetTypeDictionary.put("PRR", new String[]{ "Prairie", "Pr" });
        streetTypeDictionary.put("PRT", new String[]{ "Port", "Prt" });
        streetTypeDictionary.put("PRTS", new String[]{ "Ports", "Prts" });
        streetTypeDictionary.put("PSGE", new String[]{ "Passage", "Psge" });
        streetTypeDictionary.put("PT", new String[]{ "Point", "Pt" });
        streetTypeDictionary.put("PTS", new String[]{ "Points", "Pts" });
        streetTypeDictionary.put("PTWAY", new String[]{ "Pathway", "Ptway" });
        streetTypeDictionary.put("PVT", new String[]{ "Private", "Pvt" });
        streetTypeDictionary.put("QUAI", new String[]{ "Quai", "Quai" });
        streetTypeDictionary.put("QUAY", new String[]{ "Quay", "Quay" });
        streetTypeDictionary.put("RAD", new String[]{ "Radial", "Radl" });
        streetTypeDictionary.put("RADIAL", new String[]{ "Radial", "Radl" });
        streetTypeDictionary.put("RADIEL", new String[]{ "Radial", "Radl" });
        streetTypeDictionary.put("RADL", new String[]{ "Radial", "Radl" });
        streetTypeDictionary.put("RAMP", new String[]{ "Ramp", "Ramp" });
        streetTypeDictionary.put("RANCH", new String[]{ "Ranch", "Rnch" });
        streetTypeDictionary.put("RANCHES", new String[]{ "Ranch", "Rnch" });
        streetTypeDictionary.put("RANG", new String[]{ "Rang", "Rang" });
        streetTypeDictionary.put("RANGE", new String[]{ "Range", "Rg" });
        streetTypeDictionary.put("RAPID", new String[]{ "Rapid", "Rpd" });
        streetTypeDictionary.put("RAPIDS", new String[]{ "Rapids", "Rpds" });
        streetTypeDictionary.put("RD", new String[]{ "Road", "Rd" });
        streetTypeDictionary.put("RDG", new String[]{ "Ridge", "Rdg" });
        streetTypeDictionary.put("RDGE", new String[]{ "Ridge", "Rdg" });
        streetTypeDictionary.put("RDGS", new String[]{ "Ridges", "Rdgs" });
        streetTypeDictionary.put("RDPT", new String[]{ "Rond-Point", "Rdpt" });
        streetTypeDictionary.put("RDS", new String[]{ "Roads", "Rds" });
        streetTypeDictionary.put("REST", new String[]{ "Rest", "Rst" });
        streetTypeDictionary.put("RG", new String[]{ "Range", "Rg" });
        streetTypeDictionary.put("RIDGE", new String[]{ "Ridge", "Rdg" });
        streetTypeDictionary.put("RIDGES", new String[]{ "Ridges", "Rdgs" });
        streetTypeDictionary.put("RISE", new String[]{ "Rise", "Rise" });
        streetTypeDictionary.put("RIV", new String[]{ "River", "Riv" });
        streetTypeDictionary.put("RIVER", new String[]{ "River", "Riv" });
        streetTypeDictionary.put("RIVR", new String[]{ "River", "Riv" });
        streetTypeDictionary.put("RLE", new String[]{ "Ruelle", "Rle" });
        streetTypeDictionary.put("RNCH", new String[]{ "Ranch", "Rnch" });
        streetTypeDictionary.put("RNCHS", new String[]{ "Ranch", "Rnch" });
        streetTypeDictionary.put("ROAD", new String[]{ "Road", "Rd" });
        streetTypeDictionary.put("ROADS", new String[]{ "Roads", "Rds" });
        streetTypeDictionary.put("ROND-POINT", new String[]{ "Rond-Point", "Rdpt" });
        streetTypeDictionary.put("ROUTE", new String[]{ "Route", "Rte" });
        streetTypeDictionary.put("ROW", new String[]{ "Row", "Row" });
        streetTypeDictionary.put("RPD", new String[]{ "Rapid", "Rpd" });
        streetTypeDictionary.put("RPDS", new String[]{ "Rapids", "Rpds" });
        streetTypeDictionary.put("RST", new String[]{ "Rest", "Rst" });
        streetTypeDictionary.put("RTE", new String[]{ "Route", "Rte" });
        streetTypeDictionary.put("RUE", new String[]{ "Rue", "Rue" });
        streetTypeDictionary.put("RUELLE", new String[]{ "Ruelle", "Rle" });
        streetTypeDictionary.put("RUN", new String[]{ "Run", "Run" });
        streetTypeDictionary.put("RVR", new String[]{ "River", "Riv" });
        streetTypeDictionary.put("SENT", new String[]{ "Sentier", "Sent" });
        streetTypeDictionary.put("SENTIER", new String[]{ "Sentier", "Sent" });
        streetTypeDictionary.put("SHL", new String[]{ "Shoal", "Shl" });
        streetTypeDictionary.put("SHLS", new String[]{ "Shoals", "Shls" });
        streetTypeDictionary.put("SHOAL", new String[]{ "Shoal", "Shl" });
        streetTypeDictionary.put("SHOALS", new String[]{ "Shoals", "Shls" });
        streetTypeDictionary.put("SHOAR", new String[]{ "Shore", "Shr" });
        streetTypeDictionary.put("SHOARS", new String[]{ "Shores", "Shrs" });
        streetTypeDictionary.put("SHORE", new String[]{ "Shore", "Shr" });
        streetTypeDictionary.put("SHORES", new String[]{ "Shores", "Shrs" });
        streetTypeDictionary.put("SHR", new String[]{ "Shore", "Shr" });
        streetTypeDictionary.put("SHRS", new String[]{ "Shores", "Shrs" });
        streetTypeDictionary.put("SKWY", new String[]{ "Skyway", "Skwy" });
        streetTypeDictionary.put("SKYWAY", new String[]{ "Skyway", "Skwy" });
        streetTypeDictionary.put("SMT", new String[]{ "Summit", "Smt" });
        streetTypeDictionary.put("SPG", new String[]{ "Spring", "Spg" });
        streetTypeDictionary.put("SPGS", new String[]{ "Springs", "Spgs" });
        streetTypeDictionary.put("SPNG", new String[]{ "Spring", "Spg" });
        streetTypeDictionary.put("SPNGS", new String[]{ "Springs", "Spgs" });
        streetTypeDictionary.put("SPRING", new String[]{ "Spring", "Spg" });
        streetTypeDictionary.put("SPRINGS", new String[]{ "Springs", "Spgs" });
        streetTypeDictionary.put("SPRNG", new String[]{ "Spring", "Spg" });
        streetTypeDictionary.put("SPRNGS", new String[]{ "Springs", "Spgs" });
        streetTypeDictionary.put("SPUR", new String[]{ "Spur", "Spur" });
        streetTypeDictionary.put("SPURS", new String[]{ "Spurs", "Spur" });
        streetTypeDictionary.put("SQ", new String[]{ "Square", "Sq" });
        streetTypeDictionary.put("SQR", new String[]{ "Square", "Sq" });
        streetTypeDictionary.put("SQRE", new String[]{ "Square", "Sq" });
        streetTypeDictionary.put("SQRS", new String[]{ "Squares", "Sqs" });
        streetTypeDictionary.put("SQS", new String[]{ "Squares", "Sqs" });
        streetTypeDictionary.put("SQU", new String[]{ "Square", "Sq" });
        streetTypeDictionary.put("SQUARE", new String[]{ "Square", "Sq" });
        streetTypeDictionary.put("SQUARES", new String[]{ "Squares", "Sqs" });
        streetTypeDictionary.put("ST", new String[]{ "Street", "St" });
        streetTypeDictionary.put("STA", new String[]{ "Station", "Sta" });
        streetTypeDictionary.put("STATION", new String[]{ "Station", "Sta" });
        streetTypeDictionary.put("STATN", new String[]{ "Station", "Sta" });
        streetTypeDictionary.put("STN", new String[]{ "Station", "Sta" });
        streetTypeDictionary.put("STR", new String[]{ "Street", "St" });
        streetTypeDictionary.put("STRA", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRAV", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRAVE", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRAVEN", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRAVENUE", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRAVN", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STREAM", new String[]{ "Stream", "Strm" });
        streetTypeDictionary.put("STREET", new String[]{ "Street", "St" });
        streetTypeDictionary.put("STREETS", new String[]{ "Streets", "Sts" });
        streetTypeDictionary.put("STREME", new String[]{ "Stream", "Strm" });
        streetTypeDictionary.put("STRM", new String[]{ "Stream", "Strm" });
        streetTypeDictionary.put("STRT", new String[]{ "Street", "St" });
        streetTypeDictionary.put("STRVN", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STRVNUE", new String[]{ "Stravenue", "Stra" });
        streetTypeDictionary.put("STS", new String[]{ "Streets", "Sts" });
        streetTypeDictionary.put("SUBDIV", new String[]{ "Subdivision", "Subdiv" });
        streetTypeDictionary.put("SUBDIVISION", new String[]{ "Subdivision", "Subdiv" });
        streetTypeDictionary.put("SUMIT", new String[]{ "Summit", "Smt" });
        streetTypeDictionary.put("SUMITT", new String[]{ "Summit", "Smt" });
        streetTypeDictionary.put("SUMMIT", new String[]{ "Summit", "Smt" });
        streetTypeDictionary.put("TER", new String[]{ "Terrace", "Ter" });
        streetTypeDictionary.put("TERR", new String[]{ "Terrace", "Ter" });
        streetTypeDictionary.put("TERRACE", new String[]{ "Terrace", "Ter" });
        streetTypeDictionary.put("TERRASSE", new String[]{ "Terrasse", "Tsse" });
        streetTypeDictionary.put("THICK", new String[]{ "Thicket", "Thick" });
        streetTypeDictionary.put("THICKET", new String[]{ "Thicket", "Thick" });
        streetTypeDictionary.put("THROUGHWAY", new String[]{ "Throughway", "Trwy" });
        streetTypeDictionary.put("TLINE", new String[]{ "Townline", "Tline" });
        streetTypeDictionary.put("TOWERS", new String[]{ "Towers", "Towers" });
        streetTypeDictionary.put("TOWNLINE", new String[]{ "Townline", "Tline" });
        streetTypeDictionary.put("TPK", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("TPKE", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("TR", new String[]{ "Trail", "Trl" });
        streetTypeDictionary.put("TRACE", new String[]{ "Trace", "Trce" });
        streetTypeDictionary.put("TRACES", new String[]{ "Trace", "Trce" });
        streetTypeDictionary.put("TRACK", new String[]{ "Track", "Trak" });
        streetTypeDictionary.put("TRACKS", new String[]{ "Track", "Trak" });
        streetTypeDictionary.put("TRAFFICWAY", new String[]{ "Trafficway", "Trfy" });
        streetTypeDictionary.put("TRAIL", new String[]{ "Trail", "Trl" });
        streetTypeDictionary.put("TRAILS", new String[]{ "Trail", "Trl" });
        streetTypeDictionary.put("TRAK", new String[]{ "Track", "Trak" });
        streetTypeDictionary.put("TRCE", new String[]{ "Trace", "Trce" });
        streetTypeDictionary.put("TRFY", new String[]{ "Trafficway", "Trfy" });
        streetTypeDictionary.put("TRK", new String[]{ "Track", "Trak" });
        streetTypeDictionary.put("TRKS", new String[]{ "Track", "Trak" });
        streetTypeDictionary.put("TRL", new String[]{ "Trail", "Trl" });
        streetTypeDictionary.put("TRLS", new String[]{ "Trail", "Trl" });
        streetTypeDictionary.put("TRNABT", new String[]{ "Turnabout", "Trnabt" });
        streetTypeDictionary.put("TRNPK", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("TRPK", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("TRWY", new String[]{ "Throughway", "Trwy" });
        streetTypeDictionary.put("TSSE", new String[]{ "Terrasse", "Tsse" });
        streetTypeDictionary.put("TUNEL", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TUNL", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TUNLS", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TUNNEL", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TUNNELS", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TUNNL", new String[]{ "Tunnel", "Tunl" });
        streetTypeDictionary.put("TURNABOUT", new String[]{ "Turnabout", "Trnabt" });
        streetTypeDictionary.put("TURNPIKE", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("TURNPK", new String[]{ "Turnpike", "Tpke" });
        streetTypeDictionary.put("UN", new String[]{ "Union", "Un" });
        streetTypeDictionary.put("UNDERPASS", new String[]{ "Underpass", "Upas" });
        streetTypeDictionary.put("UNION", new String[]{ "Union", "Un" });
        streetTypeDictionary.put("UNIONS", new String[]{ "Unions", "Uns" });
        streetTypeDictionary.put("UNS", new String[]{ "Unions", "Uns" });
        streetTypeDictionary.put("UPAS", new String[]{ "Underpass", "Upas" });
        streetTypeDictionary.put("VALE", new String[]{ "Vale", "Vale" });
        streetTypeDictionary.put("VALLEY", new String[]{ "Valley", "Vly" });
        streetTypeDictionary.put("VALLEYS", new String[]{ "Valleys", "Vlys" });
        streetTypeDictionary.put("VALLY", new String[]{ "Valley", "Vly" });
        streetTypeDictionary.put("VDCT", new String[]{ "Viaduct", "Via" });
        streetTypeDictionary.put("VIA", new String[]{ "Viaduct", "Via" });
        streetTypeDictionary.put("VIADCT", new String[]{ "Viaduct", "Via" });
        streetTypeDictionary.put("VIADUCT", new String[]{ "Viaduct", "Via" });
        streetTypeDictionary.put("VIEW", new String[]{ "View", "Vw" });
        streetTypeDictionary.put("VIEWS", new String[]{ "Views", "Vws" });
        streetTypeDictionary.put("VILL", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VILLAG", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VILLAGE", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VILLAGES", new String[]{ "Villages", "Vlgs" });
        streetTypeDictionary.put("VILLAS", new String[]{ "Villas", "Villas" });
        streetTypeDictionary.put("VILLE", new String[]{ "Ville", "Vl" });
        streetTypeDictionary.put("VILLG", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VILLGE", new String[]{ "Village", "Villge" });
        streetTypeDictionary.put("VILLIAGE", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VIS", new String[]{ "Vista", "Vis" });
        streetTypeDictionary.put("VIST", new String[]{ "Vista", "Vis" });
        streetTypeDictionary.put("VISTA", new String[]{ "Vista", "Vis" });
        streetTypeDictionary.put("VL", new String[]{ "Ville", "Vl" });
        streetTypeDictionary.put("VLG", new String[]{ "Village", "Vlg" });
        streetTypeDictionary.put("VLGS", new String[]{ "Villages", "Vlgs" });
        streetTypeDictionary.put("VLLY", new String[]{ "Valley", "Vly" });
        streetTypeDictionary.put("VLY", new String[]{ "Valley", "Vly" });
        streetTypeDictionary.put("VLYS", new String[]{ "Valleys", "Vlys" });
        streetTypeDictionary.put("VOIE", new String[]{ "Voie", "Voie" });
        streetTypeDictionary.put("VST", new String[]{ "Vista", "Vis" });
        streetTypeDictionary.put("VSTA", new String[]{ "Vista", "Vis" });
        streetTypeDictionary.put("VW", new String[]{ "View", "Vw" });
        streetTypeDictionary.put("VWS", new String[]{ "Views", "Vws" });
        streetTypeDictionary.put("WALK", new String[]{ "Walk", "Walk" });
        streetTypeDictionary.put("WALKS", new String[]{ "Walks", "Walk" });
        streetTypeDictionary.put("WALL", new String[]{ "Wall", "Wall" });
        streetTypeDictionary.put("WAY", new String[]{ "Way", "Way" });
        streetTypeDictionary.put("WAYS", new String[]{ "Ways", "Ways" });
        streetTypeDictionary.put("WELL", new String[]{ "Well", "Wl" });
        streetTypeDictionary.put("WELLS", new String[]{ "Wells", "Wls" });
        streetTypeDictionary.put("WHARF", new String[]{ "Wharf", "Wharf" });
        streetTypeDictionary.put("WL", new String[]{ "Well", "Wl" });
        streetTypeDictionary.put("WLS", new String[]{ "Wells", "Wls" });
        streetTypeDictionary.put("WOOD", new String[]{ "Wood", "Wood" });
        streetTypeDictionary.put("WY", new String[]{ "Way", "Way" });
        streetTypeDictionary.put("WYND", new String[]{ "Wynd", "Wynd" });
        streetTypeDictionary.put("XING", new String[]{ "Crossing", "Xing" });
        streetTypeDictionary.put("XRD", new String[]{ "Crossroad", "Xrd" });
        return streetTypeDictionary;
    }

    public static String[] getStreetType(String streetType) throws Exception {
        streetType = removeNonLettersAndNonDigitsFromString(streetType);
        if (StringSupport.isNullOrEmpty(streetType))
            return null;
         
        String[] st = null;
        RefSupport<String[]> refVar___0 = new RefSupport<String[]>();
        getStreetTypeDictionary().TryGetValue(streetType.toUpperCase(), refVar___0);
        st = refVar___0.getValue();
        return st;
    }

    public static String[] getStreetDirection(String streetDirection) throws Exception {
        streetDirection = removeNonLettersAndNonDigitsFromString(streetDirection);
        if (StringSupport.isNullOrEmpty(streetDirection))
            return null;
         
        String[] st = null;
        RefSupport<String[]> refVar___1 = new RefSupport<String[]>();
        getstreetDirectionDictionary().TryGetValue(streetDirection.toUpperCase(), refVar___1);
        st = refVar___1.getValue();
        return st;
    }

    public static String removeNonLettersAndNonDigitsFromString(String s) throws Exception {
        if (StringSupport.isNullOrEmpty(s))
            return s;
         
        String newresult = "";
        try
        {
            for (char c : s.toCharArray())
            {
                if (Character.isLetterOrDigit(c))
                {
                    newresult += String.valueOf(c);
                }
                 
            }
        }
        catch (Exception __dummyCatchVar0)
        {
        }

        return newresult;
    }

}


